export const productData = [
  {
    id: "FILMBASE-0404",
    name: "FILMBASE 0404",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "79%",
        lightTransmittanceOff: "67%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "1800×2400mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "80%",
        lightTransmittanceOff: "68%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "1800×2400mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "83%",
        lightTransmittanceOff: "70%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "1800×2400mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },
  {
    id: "FILMBASE-0505",
    name: "FILMBASE 0505",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "80%",
        lightTransmittanceOff: "67%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×2800mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "81%",
        lightTransmittanceOff: "68%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×2800mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "84%",
        lightTransmittanceOff: "72%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×2800mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },
  {
    id: "FILMBASE-0606",
    name: "FILMBASE 0606",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "79%",
        lightTransmittanceOff: "67%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×3000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "80%",
        lightTransmittanceOff: "68%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×3000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "83%",
        lightTransmittanceOff: "70%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×3000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },
  {
    id: "FILMBASE-0808",
    name: "FILMBASE 0808",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "78%",
        lightTransmittanceOff: "64%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×4000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "79%",
        lightTransmittanceOff: "65%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×4000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "82%",
        lightTransmittanceOff: "68%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×4000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },

  {
    id: "FILMBASE-1010",
    name: "FILMBASE 1010",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "69%",
        lightTransmittanceOff: "55%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×5000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "70%",
        lightTransmittanceOff: "56%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×5000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "73%",
        lightTransmittanceOff: "59%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×5000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },
  {
    id: "FILMBASE-1212",
    name: "FILMBASE 1212",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "65%",
        lightTransmittanceOff: "49%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×6000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "66%",
        lightTransmittanceOff: "50%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×6000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "67%",
        lightTransmittanceOff: "51%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×6000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },
  {
    id: "FILMBASE-0404-Plus",
    name: "FILMBASE 0404 Plus",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "82%",
        lightTransmittanceOff: "70%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "1800×2400mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "83%",
        lightTransmittanceOff: "71%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "1800×2400mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "87%",
        lightTransmittanceOff: "75%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "1800×2400mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },
  {
    id: "FILMBASE-0505-Plus",
    name: "FILMBASE 0505 Plus",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "81%",
        lightTransmittanceOff: "69%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×2800mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "82%",
        lightTransmittanceOff: "70%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×2800mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "86%",
        lightTransmittanceOff: "74%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×2800mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: [
          "Flat",
          "Curved",
          "Tempered",
          "Ultra Clear",
          "Low-E",
          "Other",
        ],
      },
    ],
  },
  {
    id: "FILMBASE-0606-Plus",
    name: "FILMBASE 0606 Plus",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "81%",
        lightTransmittanceOff: "68%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×3000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "82%",
        lightTransmittanceOff: "69%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×3000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "86%",
        lightTransmittanceOff: "72%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×3000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
    ],
  },
  {
    id: "FILMBASE-0808-Plus",
    name: "FILMBASE 0808 Plus",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "81%",
        lightTransmittanceOff: "67%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×4000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "82%",
        lightTransmittanceOff: "68%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×4000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "84%",
        lightTransmittanceOff: "71%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×4000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
    ],
  },
  {
    id: "FILMBASE-1010-Plus",
    name: "FILMBASE 1010 Plus",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "80%",
        lightTransmittanceOff: "64%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×5000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "81%",
        lightTransmittanceOff: "65%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×5000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "85%",
        lightTransmittanceOff: "67%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×5000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
    ],
  },
  {
    id: "FILMBASE-1212-Plus",
    name: "FILMBASE 1212 Plus",
    products: [
      {
        model: "085 PDLC film",
        filmColor: "White",
        hazeOn: "6%",
        hazeOff: "94%",
        lightTransmittanceOn: "80%",
        lightTransmittanceOff: "61%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×6000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "087 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "81%",
        lightTransmittanceOff: "62%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva",
        biggestSize: "2000×4000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
      {
        model: "091 PDLC film",
        filmColor: "White",
        hazeOn: "4%",
        hazeOff: "94%",
        lightTransmittanceOn: "84%",
        lightTransmittanceOff: "65%",
        uvBlock: ">99%",
        irBlock: ">86%",
        powerConsumption: "5w/m²",
        compatibleWith: "Eva, Super clear glass",
        biggestSize: "2000×6000mm",
        inputVoltage: "100-120v 60Hz / 220-240v 50Hz",
        glassTypes: ["Flat", "Curved", "Tempered", "Ultra Clear", "Low-E", "Other"],
      },
    ],
  },  
];
